### PR TITLE
Add SChinese translation of website

### PR DESCRIPTION
**Pull request by LezaiYa1**
All SChinese translations from crowdin

### CODE REVIEW

**Comment by LezaiYa1** [comment]
All contributors to the website translated into SChinese: _Sheep_、_xqw_、_ninyouyigehao_、_hujia898_、_LezaiYa_、_JJJJGGGG12345_、_CrewCyan_、_hhg_、_xiaoxiangren_、_yuebing_、_xianpisa_

**Comment by LezaiYa1** [comment]
It took us 3 days to complete all the translations!
At present, the accuracy rate of translation is not high
If moe you need to update the website
You can merge this PR first
The accuracy of the translation is slowly revised

**Comment by 0xDrMoe** [comment]
Why is there two folders? One zh-CN and one in Chinese (that i can't read)

**Comment by LezaiYa1** [comment]
> Why is there two folders? One zh-CN and one in Chinese (that i can't read)

I changed the zh-CN folder to "简体中文"(SChinese).

**Pull request closed without merging**
