### PR TITLE
Clickable Role Camps + Dev Build Update

### PR DESCRIPTION
**Pull request by MargaretTheFool**
Made the camps (Add-ons, Crewmates, etc.) on https://tohre.dev/Roles.html clickable links
Also updated it with the most recent dev build

### CODE REVIEW

**Comment by pyrosliced** [comment]
Merge this into 0xDrMoe:beta rather than 0xDrMoe:main, since main is live on site and beta is, well beta.

**Comment by MargaretTheFool** [comment]
done

**Comment by pyrosliced** [comment]
> done

Now you just wait roughly 5 days until Moe remembers to forget to forget about the site github

**Review by 0xDrMoe — CHANGES_REQUESTED** [review]
This needs to be updated as we changed the roles.md file

**Comment by MargaretTheFool** [comment]
i changed one thing and now everything has a conflict what

**Pull request closed without merging**
